/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as HomeRouteImport } from './routes/home'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OrganizerRouteImport } from './routes/organizer'
import { Route as OrganizerAttendeesRouteImport } from './routes/organizer-attendees'
import { Route as OrganizerCreateRouteImport } from './routes/organizer-create'
import { Route as OrganizerEventDetailRouteImport } from './routes/organizer-event-detail'
import { Route as OrganizerEventsRouteImport } from './routes/organizer-events'
import { Route as OrganizerInvitationsRouteImport } from './routes/organizer-invitations'
import { Route as OrganizerProfileRouteImport } from './routes/organizer-profile'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as EventEventIdRouteImport } from './routes/event/$eventId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerRoute = OrganizerRouteImport.update({
  id: '/organizer',
  path: '/organizer',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerAttendeesRoute = OrganizerAttendeesRouteImport.update({
  id: '/organizer-attendees',
  path: '/organizer-attendees',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerCreateRoute = OrganizerCreateRouteImport.update({
  id: '/organizer-create',
  path: '/organizer-create',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerEventDetailRoute = OrganizerEventDetailRouteImport.update({
  id: '/organizer-event-detail',
  path: '/organizer-event-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerEventsRoute = OrganizerEventsRouteImport.update({
  id: '/organizer-events',
  path: '/organizer-events',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerInvitationsRoute = OrganizerInvitationsRouteImport.update({
  id: '/organizer-invitations',
  path: '/organizer-invitations',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerProfileRoute = OrganizerProfileRouteImport.update({
  id: '/organizer-profile',
  path: '/organizer-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const EventEventIdRoute = EventEventIdRouteImport.update({
  id: '/event/$eventId',
  path: '/event/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/explore': typeof ExploreRoute
  '/friends': typeof FriendsRoute
  '/home': typeof HomeRoute
  '/notifications': typeof NotificationsRoute
  '/organizer': typeof OrganizerRoute
  '/organizer-attendees': typeof OrganizerAttendeesRoute
  '/organizer-create': typeof OrganizerCreateRoute
  '/organizer-event-detail': typeof OrganizerEventDetailRoute
  '/organizer-events': typeof OrganizerEventsRoute
  '/organizer-invitations': typeof OrganizerInvitationsRoute
  '/organizer-profile': typeof OrganizerProfileRoute
  '/profile': typeof ProfileRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/event/$eventId': typeof EventEventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/explore': typeof ExploreRoute
  '/friends': typeof FriendsRoute
  '/home': typeof HomeRoute
  '/notifications': typeof NotificationsRoute
  '/organizer': typeof OrganizerRoute
  '/organizer-attendees': typeof OrganizerAttendeesRoute
  '/organizer-create': typeof OrganizerCreateRoute
  '/organizer-event-detail': typeof OrganizerEventDetailRoute
  '/organizer-events': typeof OrganizerEventsRoute
  '/organizer-invitations': typeof OrganizerInvitationsRoute
  '/organizer-profile': typeof OrganizerProfileRoute
  '/profile': typeof ProfileRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/event/$eventId': typeof EventEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/explore': typeof ExploreRoute
  '/friends': typeof FriendsRoute
  '/home': typeof HomeRoute
  '/notifications': typeof NotificationsRoute
  '/organizer': typeof OrganizerRoute
  '/organizer-attendees': typeof OrganizerAttendeesRoute
  '/organizer-create': typeof OrganizerCreateRoute
  '/organizer-event-detail': typeof OrganizerEventDetailRoute
  '/organizer-events': typeof OrganizerEventsRoute
  '/organizer-invitations': typeof OrganizerInvitationsRoute
  '/organizer-profile': typeof OrganizerProfileRoute
  '/profile': typeof ProfileRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/event/$eventId': typeof EventEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events'
    | '/explore'
    | '/friends'
    | '/home'
    | '/notifications'
    | '/organizer'
    | '/organizer-attendees'
    | '/organizer-create'
    | '/organizer-event-detail'
    | '/organizer-events'
    | '/organizer-invitations'
    | '/organizer-profile'
    | '/profile'
    | '/signin'
    | '/signup'
    | '/event/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events'
    | '/explore'
    | '/friends'
    | '/home'
    | '/notifications'
    | '/organizer'
    | '/organizer-attendees'
    | '/organizer-create'
    | '/organizer-event-detail'
    | '/organizer-events'
    | '/organizer-invitations'
    | '/organizer-profile'
    | '/profile'
    | '/signin'
    | '/signup'
    | '/event/$eventId'
  id:
    | '__root__'
    | '/'
    | '/events'
    | '/explore'
    | '/friends'
    | '/home'
    | '/notifications'
    | '/organizer'
    | '/organizer-attendees'
    | '/organizer-create'
    | '/organizer-event-detail'
    | '/organizer-events'
    | '/organizer-invitations'
    | '/organizer-profile'
    | '/profile'
    | '/signin'
    | '/signup'
    | '/event/$eventId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsRoute: typeof EventsRoute
  ExploreRoute: typeof ExploreRoute
  FriendsRoute: typeof FriendsRoute
  HomeRoute: typeof HomeRoute
  NotificationsRoute: typeof NotificationsRoute
  OrganizerRoute: typeof OrganizerRoute
  OrganizerAttendeesRoute: typeof OrganizerAttendeesRoute
  OrganizerCreateRoute: typeof OrganizerCreateRoute
  OrganizerEventDetailRoute: typeof OrganizerEventDetailRoute
  OrganizerEventsRoute: typeof OrganizerEventsRoute
  OrganizerInvitationsRoute: typeof OrganizerInvitationsRoute
  OrganizerProfileRoute: typeof OrganizerProfileRoute
  ProfileRoute: typeof ProfileRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  EventEventIdRoute: typeof EventEventIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer': {
      id: '/organizer'
      path: '/organizer'
      fullPath: '/organizer'
      preLoaderRoute: typeof OrganizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer-attendees': {
      id: '/organizer-attendees'
      path: '/organizer-attendees'
      fullPath: '/organizer-attendees'
      preLoaderRoute: typeof OrganizerAttendeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer-create': {
      id: '/organizer-create'
      path: '/organizer-create'
      fullPath: '/organizer-create'
      preLoaderRoute: typeof OrganizerCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer-event-detail': {
      id: '/organizer-event-detail'
      path: '/organizer-event-detail'
      fullPath: '/organizer-event-detail'
      preLoaderRoute: typeof OrganizerEventDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer-events': {
      id: '/organizer-events'
      path: '/organizer-events'
      fullPath: '/organizer-events'
      preLoaderRoute: typeof OrganizerEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer-invitations': {
      id: '/organizer-invitations'
      path: '/organizer-invitations'
      fullPath: '/organizer-invitations'
      preLoaderRoute: typeof OrganizerInvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer-profile': {
      id: '/organizer-profile'
      path: '/organizer-profile'
      fullPath: '/organizer-profile'
      preLoaderRoute: typeof OrganizerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$eventId': {
      id: '/event/$eventId'
      path: '/event/$eventId'
      fullPath: '/event/$eventId'
      preLoaderRoute: typeof EventEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsRoute: EventsRoute,
  ExploreRoute: ExploreRoute,
  FriendsRoute: FriendsRoute,
  HomeRoute: HomeRoute,
  NotificationsRoute: NotificationsRoute,
  OrganizerRoute: OrganizerRoute,
  OrganizerAttendeesRoute: OrganizerAttendeesRoute,
  OrganizerCreateRoute: OrganizerCreateRoute,
  OrganizerEventDetailRoute: OrganizerEventDetailRoute,
  OrganizerEventsRoute: OrganizerEventsRoute,
  OrganizerInvitationsRoute: OrganizerInvitationsRoute,
  OrganizerProfileRoute: OrganizerProfileRoute,
  ProfileRoute: ProfileRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  EventEventIdRoute: EventEventIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
